/* Generated By:JavaCC: Do not edit this line. ParserXMLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserXMLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 6;
  /** RegularExpression Id. */
  int digito = 7;
  /** RegularExpression Id. */
  int _text = 8;
  /** RegularExpression Id. */
  int _integer = 9;
  /** RegularExpression Id. */
  int _double = 10;
  /** RegularExpression Id. */
  int _bool = 11;
  /** RegularExpression Id. */
  int _date = 12;
  /** RegularExpression Id. */
  int _datetime = 13;
  /** RegularExpression Id. */
  int pk = 14;
  /** RegularExpression Id. */
  int fk = 15;
  /** RegularExpression Id. */
  int nulo = 16;
  /** RegularExpression Id. */
  int nonulo = 17;
  /** RegularExpression Id. */
  int unico = 18;
  /** RegularExpression Id. */
  int autoinc = 19;
  /** RegularExpression Id. */
  int entero = 20;
  /** RegularExpression Id. */
  int doble = 21;
  /** RegularExpression Id. */
  int booleano = 22;
  /** RegularExpression Id. */
  int fecha = 23;
  /** RegularExpression Id. */
  int fecha_hora = 24;
  /** RegularExpression Id. */
  int cadena = 25;
  /** RegularExpression Id. */
  int codigo = 26;
  /** RegularExpression Id. */
  int id = 27;
  /** RegularExpression Id. */
  int path = 28;
  /** RegularExpression Id. */
  int open = 29;
  /** RegularExpression Id. */
  int close = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "<letra>",
    "<digito>",
    "\"Text\"",
    "\"Integer\"",
    "\"Double\"",
    "\"Bool\"",
    "\"Date\"",
    "\"DateTime\"",
    "\"PK\"",
    "\"FK\"",
    "\"NULL\"",
    "\"NOT NULLL\"",
    "\"UNIQUE\"",
    "\"AUTOINC\"",
    "<entero>",
    "<doble>",
    "<booleano>",
    "<fecha>",
    "<fecha_hora>",
    "<cadena>",
    "<codigo>",
    "<id>",
    "<path>",
    "<open>",
    "<close>",
    "\"<MasterFile>\"",
    "\"</MasterFile>\"",
    "\"<db>\"",
    "\"<name>\"",
    "\"</name>\"",
    "\"<path>\"",
    "\"</path>\"",
    "\"</db>\"",
    "\"<UsersFile>\"",
    "\"</UsersFile>\"",
    "\"<user>\"",
    "\"<password>\"",
    "\"</password>\"",
    "\"</user>\"",
    "\"<DataBaseFile>\"",
    "\"<procedures>\"",
    "\"</procedures>\"",
    "\"<objects>\"",
    "\"</objects>\"",
    "\"</DataBaseFile>\"",
    "\"<table>\"",
    "\"<rows>\"",
    "\"</rows>\"",
    "\"</table>\"",
    "\"<row>\"",
    "\"<type>\"",
    "\"</type>\"",
    "\"</row>\"",
    "\"<complementos>\"",
    "\"</complementos>\"",
    "\"<complemento>\"",
    "\"</complemento>\"",
    "\"<TableFile>\"",
    "\"</TableFile>\"",
    "\"<field>\"",
    "\"<value>\"",
    "\"</value>\"",
    "\"</field>\"",
    "\"<MethodFile>\"",
    "\"</MethodFile>\"",
    "\"<method>\"",
    "\"<arguments>\"",
    "\"</arguments>\"",
    "\"<src>\"",
    "\"</src>\"",
    "\"</method>\"",
    "\"<argument>\"",
    "\"</argument>\"",
    "\"<ObjectFile>\"",
    "\"</ObjectFile>\"",
    "\"<object>\"",
    "\"<attributes>\"",
    "\"</attributes>\"",
    "\"</object>\"",
    "\"<attribute>\"",
    "\"</attribute>\"",
    "\"<permissions>\"",
    "\"</permissions>\"",
  };

}
