/* Generated By:JavaCC: Do not edit this line. ParserXML.java */
        public class ParserXML implements ParserXMLConstants {
                public static void main(String[] args) throws ParseException{
                                try{
                                        ParserXML parser = new ParserXML(System.in);
                                        parser.INI();
                                }catch(ParseException pe){
                                        System.err.println("Error en el analisis...");
                                        System.err.println(pe.getMessage());
                                }
                        }

  final public void INI() throws ParseException {
    XML();
    jj_consume_token(0);
  }

  final public void XML() throws ParseException {
    jj_consume_token(open);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case _text:
      case _integer:
      case _double:
      case _bool:
      case _date:
      case _datetime:
      case pk:
      case fk:
      case nulo:
      case nonulo:
      case unico:
      case autoinc:
      case entero:
      case doble:
      case booleano:
      case fecha:
      case fecha_hora:
      case cadena:
      case codigo:
      case id:
      case path:
        CONTENT();
        break;
      case open:
        XML();
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case _text:
      case _integer:
      case _double:
      case _bool:
      case _date:
      case _datetime:
      case pk:
      case fk:
      case nulo:
      case nonulo:
      case unico:
      case autoinc:
      case entero:
      case doble:
      case booleano:
      case fecha:
      case fecha_hora:
      case cadena:
      case codigo:
      case id:
      case path:
      case open:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }
    jj_consume_token(close);
  }

  final public void CONTENT() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case entero:
    case doble:
    case booleano:
    case fecha:
    case fecha_hora:
    case cadena:
      VALUE();
      break;
    case _text:
    case _integer:
    case _double:
    case _bool:
    case _date:
    case _datetime:
      TIPO();
      break;
    case pk:
    case fk:
    case nulo:
    case nonulo:
    case unico:
    case autoinc:
      COMPLEMENT();
      break;
    case id:
      jj_consume_token(id);
      break;
    case codigo:
      jj_consume_token(codigo);
      break;
    case path:
      jj_consume_token(path);
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void FILE() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 31:
      MASTER();
      break;
    case 39:
      USERS();
      break;
    case 45:
      DB();
      break;
    case 63:
      TABLE();
      break;
    case 69:
      METHOD();
      break;
    case 79:
      OBJECT();
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/**************************************************************************************************************
MASTER
**************************************************************************************************************/
  final public void MASTER() throws ParseException {
    jj_consume_token(31);
    label_2:
    while (true) {
      L_DB();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 33:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_2;
      }
    }
    jj_consume_token(32);
  }

  final public void L_DB() throws ParseException {
    jj_consume_token(33);
    jj_consume_token(34);
    jj_consume_token(id);
    jj_consume_token(35);
    jj_consume_token(36);
    jj_consume_token(path);
    jj_consume_token(37);
    jj_consume_token(38);
  }

/**************************************************************************************************************
USERS
**************************************************************************************************************/
  final public void USERS() throws ParseException {
    jj_consume_token(39);
    label_3:
    while (true) {
      USER();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 41:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_3;
      }
    }
    jj_consume_token(40);
  }

  final public void USER() throws ParseException {
    jj_consume_token(41);
    USERNAME();
    jj_consume_token(42);
    jj_consume_token(id);
    jj_consume_token(43);
    jj_consume_token(44);
  }

  final public void USERNAME() throws ParseException {
    jj_consume_token(34);
    jj_consume_token(id);
    jj_consume_token(35);
  }

/**************************************************************************************************************
DB
**************************************************************************************************************/
  final public void DB() throws ParseException {
    jj_consume_token(45);
    PERMISSIONS();
    jj_consume_token(46);
    jj_consume_token(36);
    jj_consume_token(path);
    jj_consume_token(37);
    jj_consume_token(47);
    jj_consume_token(48);
    jj_consume_token(36);
    jj_consume_token(path);
    jj_consume_token(37);
    jj_consume_token(49);
    label_4:
    while (true) {
      DB_TABLE();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 51:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_4;
      }
    }
    jj_consume_token(50);
  }

  final public void DB_TABLE() throws ParseException {
    jj_consume_token(51);
    PERMISSIONS();
    jj_consume_token(34);
    jj_consume_token(id);
    jj_consume_token(35);
    jj_consume_token(36);
    jj_consume_token(path);
    jj_consume_token(37);
    jj_consume_token(52);
    label_5:
    while (true) {
      ROWSDEF();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 55:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_5;
      }
    }
    jj_consume_token(53);
    jj_consume_token(54);
  }

  final public void ROWSDEF() throws ParseException {
    jj_consume_token(55);
    jj_consume_token(56);
    TIPO();
    jj_consume_token(57);
    jj_consume_token(34);
    jj_consume_token(id);
    jj_consume_token(35);
    jj_consume_token(58);
  }

  final public void COMPLEMENTOS() throws ParseException {
    jj_consume_token(59);
    label_6:
    while (true) {
      COMPLEMENTO();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 61:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_6;
      }
    }
    jj_consume_token(60);
  }

  final public void COMPLEMENTO() throws ParseException {
    jj_consume_token(61);
    COMPLEMENT();
    jj_consume_token(62);
  }

  final public void COMPLEMENT() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case pk:
      jj_consume_token(pk);
      break;
    case fk:
      jj_consume_token(fk);
      break;
    case nulo:
      jj_consume_token(nulo);
      break;
    case nonulo:
      jj_consume_token(nonulo);
      break;
    case unico:
      jj_consume_token(unico);
      break;
    case autoinc:
      jj_consume_token(autoinc);
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/**************************************************************************************************************
TABLE
**************************************************************************************************************/
  final public void TABLE() throws ParseException {
    jj_consume_token(63);
    label_7:
    while (true) {
      ROW();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 55:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_7;
      }
    }
    jj_consume_token(64);
  }

  final public void ROW() throws ParseException {
    jj_consume_token(55);
    label_8:
    while (true) {
      FIELD();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 65:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_8;
      }
    }
    jj_consume_token(58);
  }

  final public void FIELD() throws ParseException {
    jj_consume_token(65);
    jj_consume_token(34);
    jj_consume_token(id);
    jj_consume_token(35);
    jj_consume_token(66);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case entero:
    case doble:
    case booleano:
    case fecha:
    case fecha_hora:
    case cadena:
      VALUE();
      break;
    default:
      jj_la1[12] = jj_gen;
      ;
    }
    jj_consume_token(67);
    jj_consume_token(68);
  }

/**************************************************************************************************************
METHOD
**************************************************************************************************************/
  final public void METHOD() throws ParseException {
    jj_consume_token(69);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 71:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_9;
      }
      METODO();
    }
    jj_consume_token(70);
  }

  final public void METODO() throws ParseException {
    jj_consume_token(71);
    PERMISSIONS();
    jj_consume_token(34);
    jj_consume_token(id);
    jj_consume_token(35);
    jj_consume_token(72);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 77:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_10;
      }
      ARGUMENTS();
    }
    jj_consume_token(73);
    jj_consume_token(74);
    jj_consume_token(codigo);
    jj_consume_token(75);
    jj_consume_token(76);
  }

  final public void ARGUMENTS() throws ParseException {
    jj_consume_token(77);
    jj_consume_token(56);
    TIPO();
    jj_consume_token(57);
    jj_consume_token(34);
    jj_consume_token(id);
    jj_consume_token(35);
    jj_consume_token(78);
  }

/**************************************************************************************************************
OBJECT
**************************************************************************************************************/
  final public void OBJECT() throws ParseException {
    jj_consume_token(79);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 81:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_11;
      }
      OBJETO();
    }
    jj_consume_token(80);
  }

  final public void OBJETO() throws ParseException {
    jj_consume_token(81);
    PERMISSIONS();
    jj_consume_token(34);
    jj_consume_token(id);
    jj_consume_token(35);
    jj_consume_token(82);
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 85:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_12;
      }
      ATTRIBUTES();
    }
    jj_consume_token(83);
    jj_consume_token(84);
  }

  final public void ATTRIBUTES() throws ParseException {
    jj_consume_token(85);
    jj_consume_token(56);
    TIPO();
    jj_consume_token(57);
    jj_consume_token(34);
    jj_consume_token(id);
    jj_consume_token(35);
    jj_consume_token(86);
  }

/**************************************************************************************************************
COMUN
**************************************************************************************************************/
  final public void PERMISSIONS() throws ParseException {
    jj_consume_token(87);
    label_13:
    while (true) {
      USERNAME();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 34:
        ;
        break;
      default:
        jj_la1[17] = jj_gen;
        break label_13;
      }
    }
    jj_consume_token(88);
  }

  final public void TIPO() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case _text:
      jj_consume_token(_text);
      break;
    case _integer:
      jj_consume_token(_integer);
      break;
    case _double:
      jj_consume_token(_double);
      break;
    case _bool:
      jj_consume_token(_bool);
      break;
    case _date:
      jj_consume_token(_date);
      break;
    case _datetime:
      jj_consume_token(_datetime);
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void VALUE() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case cadena:
      jj_consume_token(cadena);
      break;
    case entero:
      jj_consume_token(entero);
      break;
    case doble:
      jj_consume_token(doble);
      break;
    case booleano:
      jj_consume_token(booleano);
      break;
    case fecha:
      jj_consume_token(fecha);
      break;
    case fecha_hora:
      jj_consume_token(fecha_hora);
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  /** Generated Token Manager. */
  public ParserXMLTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[20];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x3fffff00,0x3fffff00,0x1fffff00,0x80000000,0x0,0x0,0x0,0x0,0x0,0xfc000,0x0,0x0,0x3f00000,0x0,0x0,0x0,0x0,0x0,0x3f00,0x3f00000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x80002080,0x2,0x200,0x80000,0x800000,0x20000000,0x0,0x800000,0x0,0x0,0x0,0x0,0x0,0x0,0x4,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x8020,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x80,0x2000,0x20000,0x200000,0x0,0x0,0x0,};
   }

  /** Constructor with InputStream. */
  public ParserXML(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public ParserXML(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserXMLTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public ParserXML(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserXMLTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public ParserXML(ParserXMLTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ParserXMLTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[89];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 20; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 89; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

                }
