/* Generated By:JavaCC: Do not edit this line. ParserXMLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserXMLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 5;
  /** RegularExpression Id. */
  int digito = 6;
  /** RegularExpression Id. */
  int _text = 7;
  /** RegularExpression Id. */
  int _integer = 8;
  /** RegularExpression Id. */
  int _double = 9;
  /** RegularExpression Id. */
  int _bool = 10;
  /** RegularExpression Id. */
  int _date = 11;
  /** RegularExpression Id. */
  int _datetime = 12;
  /** RegularExpression Id. */
  int entero = 13;
  /** RegularExpression Id. */
  int doble = 14;
  /** RegularExpression Id. */
  int booleano = 15;
  /** RegularExpression Id. */
  int fecha = 16;
  /** RegularExpression Id. */
  int fecha_hora = 17;
  /** RegularExpression Id. */
  int cadena = 18;
  /** RegularExpression Id. */
  int codigo = 19;
  /** RegularExpression Id. */
  int id = 20;
  /** RegularExpression Id. */
  int path = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "<letra>",
    "<digito>",
    "\"Text\"",
    "\"Integer\"",
    "\"Double\"",
    "\"Bool\"",
    "\"Date\"",
    "\"DateTime\"",
    "<entero>",
    "<doble>",
    "<booleano>",
    "<fecha>",
    "<fecha_hora>",
    "<cadena>",
    "<codigo>",
    "<id>",
    "<path>",
    "\"<MasterFile>\"",
    "\"</MasterFile>\"",
    "\"<db>\"",
    "\"<name>\"",
    "\"</name>\"",
    "\"<path>\"",
    "\"</path>\"",
    "\"</db>\"",
    "\"<DataBaseFile>\"",
    "\"<procedures>\"",
    "\"</procedures>\"",
    "\"<objects>\"",
    "\"</objects>\"",
    "\"</DataBaseFile>\"",
    "\"<table>\"",
    "\"<rows>\"",
    "\"</rows>\"",
    "\"</table>\"",
    "\"<row>\"",
    "\"<type>\"",
    "\"</type>\"",
    "\"</row>\"",
    "\"<TableFile>\"",
    "\"</TableFile>\"",
    "\"<field>\"",
    "\"<value>\"",
    "\"</value>\"",
    "\"</field>\"",
    "\"<MethodFile>\"",
    "\"</MethodFile>\"",
    "\"<method>\"",
    "\"<arguments>\"",
    "\"</arguments>\"",
    "\"<src>\"",
    "\"</src>\"",
    "\"</method>\"",
    "\"<argument>\"",
    "\"</argument>\"",
    "\"<ObjectFile>\"",
    "\"</ObjectFile>\"",
    "\"<object>\"",
    "\"<attributes>\"",
    "\"</attributes>\"",
    "\"</object>\"",
    "\"<attribute>\"",
    "\"</attribute>\"",
  };

}
