/* Generated By:JavaCC: Do not edit this line. ParserPlyCSConstants.java */
package servidorfisql.interpretes.Analizadores.PlyCS.analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserPlyCSConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int num = 5;
  /** RegularExpression Id. */
  int bool = 6;
  /** RegularExpression Id. */
  int cad = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "<num>",
    "<bool>",
    "<cad>",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\":\"",
  };

}
