/* Generated By:JavaCC: Do not edit this line. ParserPlyCSConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserPlyCSConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int coma = 5;
  /** RegularExpression Id. */
  int caracter = 6;
  /** RegularExpression Id. */
  int entero = 7;
  /** RegularExpression Id. */
  int id = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\",\"",
    "\"char\"",
    "\"int\"",
    "<id>",
  };

}
