/* Generated By:JavaCC: Do not edit this line. ParserXMLConstants.java */
package servidorfisql.interpretes.Analizadores.XML.analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserXMLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 5;
  /** RegularExpression Id. */
  int digito = 6;
  /** RegularExpression Id. */
  int _text = 7;
  /** RegularExpression Id. */
  int _integer = 8;
  /** RegularExpression Id. */
  int _double = 9;
  /** RegularExpression Id. */
  int _bool = 10;
  /** RegularExpression Id. */
  int _date = 11;
  /** RegularExpression Id. */
  int _datetime = 12;
  /** RegularExpression Id. */
  int pk = 13;
  /** RegularExpression Id. */
  int fk = 14;
  /** RegularExpression Id. */
  int nulo = 15;
  /** RegularExpression Id. */
  int nonulo = 16;
  /** RegularExpression Id. */
  int unico = 17;
  /** RegularExpression Id. */
  int autoinc = 18;
  /** RegularExpression Id. */
  int entero = 19;
  /** RegularExpression Id. */
  int doble = 20;
  /** RegularExpression Id. */
  int booleano = 21;
  /** RegularExpression Id. */
  int fecha = 22;
  /** RegularExpression Id. */
  int fecha_hora = 23;
  /** RegularExpression Id. */
  int cadena = 24;
  /** RegularExpression Id. */
  int codigo = 25;
  /** RegularExpression Id. */
  int id = 26;
  /** RegularExpression Id. */
  int path = 27;
  /** RegularExpression Id. */
  int open = 28;
  /** RegularExpression Id. */
  int close = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "<letra>",
    "<digito>",
    "\"Text\"",
    "\"Integer\"",
    "\"Double\"",
    "\"Bool\"",
    "\"Date\"",
    "\"DateTime\"",
    "\"PK\"",
    "\"FK\"",
    "\"NULL\"",
    "\"NOT NULLL\"",
    "\"UNIQUE\"",
    "\"AUTOINC\"",
    "<entero>",
    "<doble>",
    "<booleano>",
    "<fecha>",
    "<fecha_hora>",
    "<cadena>",
    "<codigo>",
    "<id>",
    "<path>",
    "<open>",
    "<close>",
  };

}
