/* Generated By:JavaCC: Do not edit this line. ParserUSQLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserUSQLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int letra = 11;
  /** RegularExpression Id. */
  int digito = 12;
  /** RegularExpression Id. */
  int _text = 13;
  /** RegularExpression Id. */
  int _integer = 14;
  /** RegularExpression Id. */
  int _double = 15;
  /** RegularExpression Id. */
  int _bool = 16;
  /** RegularExpression Id. */
  int _date = 17;
  /** RegularExpression Id. */
  int _datetime = 18;
  /** RegularExpression Id. */
  int crear = 19;
  /** RegularExpression Id. */
  int usar = 20;
  /** RegularExpression Id. */
  int alterar = 21;
  /** RegularExpression Id. */
  int eliminar = 22;
  /** RegularExpression Id. */
  int base_datos = 23;
  /** RegularExpression Id. */
  int tabla = 24;
  /** RegularExpression Id. */
  int objeto = 25;
  /** RegularExpression Id. */
  int procedimiento = 26;
  /** RegularExpression Id. */
  int funcion = 27;
  /** RegularExpression Id. */
  int usuario = 28;
  /** RegularExpression Id. */
  int nulo = 29;
  /** RegularExpression Id. */
  int no_nulo = 30;
  /** RegularExpression Id. */
  int llave_primaria = 31;
  /** RegularExpression Id. */
  int llave_foranea = 32;
  /** RegularExpression Id. */
  int unico = 33;
  /** RegularExpression Id. */
  int autoincrementable = 34;
  /** RegularExpression Id. */
  int colocar = 35;
  /** RegularExpression Id. */
  int password = 36;
  /** RegularExpression Id. */
  int quitar = 37;
  /** RegularExpression Id. */
  int agregar = 38;
  /** RegularExpression Id. */
  int cambiar = 39;
  /** RegularExpression Id. */
  int insertar = 40;
  /** RegularExpression Id. */
  int seleccionar = 41;
  /** RegularExpression Id. */
  int actualizar = 42;
  /** RegularExpression Id. */
  int borrar = 43;
  /** RegularExpression Id. */
  int en = 44;
  /** RegularExpression Id. */
  int de = 45;
  /** RegularExpression Id. */
  int donde = 46;
  /** RegularExpression Id. */
  int valores = 47;
  /** RegularExpression Id. */
  int ordenar = 48;
  /** RegularExpression Id. */
  int por = 49;
  /** RegularExpression Id. */
  int asc = 50;
  /** RegularExpression Id. */
  int desc = 51;
  /** RegularExpression Id. */
  int otorgar = 52;
  /** RegularExpression Id. */
  int denegar = 53;
  /** RegularExpression Id. */
  int permisos = 54;
  /** RegularExpression Id. */
  int backup = 55;
  /** RegularExpression Id. */
  int restaurar = 56;
  /** RegularExpression Id. */
  int usqldump = 57;
  /** RegularExpression Id. */
  int completo = 58;
  /** RegularExpression Id. */
  int declarar = 59;
  /** RegularExpression Id. */
  int si = 60;
  /** RegularExpression Id. */
  int sino = 61;
  /** RegularExpression Id. */
  int para = 62;
  /** RegularExpression Id. */
  int selecciona = 63;
  /** RegularExpression Id. */
  int caso = 64;
  /** RegularExpression Id. */
  int defecto = 65;
  /** RegularExpression Id. */
  int mientras = 66;
  /** RegularExpression Id. */
  int detener = 67;
  /** RegularExpression Id. */
  int retorno = 68;
  /** RegularExpression Id. */
  int contar = 69;
  /** RegularExpression Id. */
  int imprimir = 70;
  /** RegularExpression Id. */
  int get_fecha = 71;
  /** RegularExpression Id. */
  int get_fecha_hora = 72;
  /** RegularExpression Id. */
  int entero = 73;
  /** RegularExpression Id. */
  int doble = 74;
  /** RegularExpression Id. */
  int booleano = 75;
  /** RegularExpression Id. */
  int fecha = 76;
  /** RegularExpression Id. */
  int fecha_hora = 77;
  /** RegularExpression Id. */
  int cadena = 78;
  /** RegularExpression Id. */
  int id = 79;
  /** RegularExpression Id. */
  int var = 80;
  /** RegularExpression Id. */
  int path = 81;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"#\"",
    "\"#*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*#\"",
    "<token of kind 10>",
    "<letra>",
    "<digito>",
    "\"Text\"",
    "\"Integer\"",
    "\"Double\"",
    "\"Bool\"",
    "\"Date\"",
    "\"DateTime\"",
    "\"CREAR\"",
    "\"USAR\"",
    "\"ALTERAR\"",
    "\"ELIMINAR\"",
    "\"BASE_DATOS\"",
    "\"TABLA\"",
    "\"OBJETO\"",
    "\"PROCEDIMIENTO\"",
    "\"FUNCION\"",
    "\"USUARIO\"",
    "\"Nulo\"",
    "\"No Nulo\"",
    "\"Llave_primaria\"",
    "\"Llave_foranea\"",
    "\"Unico\"",
    "\"Autoincrementable\"",
    "\"COLOCAR\"",
    "\"password\"",
    "\"QUITAR\"",
    "\"AGREGAR\"",
    "\"CAMBIAR\"",
    "\"INSERTAR\"",
    "\"SELECCIONAR\"",
    "\"ACTUALIZAR\"",
    "\"BORRAR\"",
    "\"EN\"",
    "\"DE\"",
    "\"DONDE\"",
    "\"VALORES\"",
    "\"ORDENAR\"",
    "\"POR\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"OTORGAR\"",
    "\"DENEGAR\"",
    "\"PERMISOS\"",
    "\"BACKUP\"",
    "\"RESTAURAR\"",
    "\"USQLDUMP\"",
    "\"COMPLETO\"",
    "\"DECLARAR\"",
    "\"SI\"",
    "\"SINO\"",
    "\"PARA\"",
    "\"SELECCIONA\"",
    "\"CASO\"",
    "\"DEFECTO\"",
    "\"MIENTRAS\"",
    "\"DETENER\"",
    "\"RETORNO\"",
    "\"CONTAR\"",
    "\"IMPRIMIR\"",
    "\"FECHA\"",
    "\"FECHA_HORA\"",
    "<entero>",
    "<doble>",
    "<booleano>",
    "<fecha>",
    "<fecha_hora>",
    "<cadena>",
    "<id>",
    "<var>",
    "<path>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=\"",
    "\"*\"",
    "\".\"",
    "\"{\"",
    "\":\"",
    "\"}\"",
    "\"++\"",
    "\"--\"",
    "\"<<\"",
    "\">>\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"^\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
  };

}
