/* Generated By:JavaCC: Do not edit this line. ParserUSQLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserUSQLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int letra = 7;
  /** RegularExpression Id. */
  int digito = 8;
  /** RegularExpression Id. */
  int _text = 9;
  /** RegularExpression Id. */
  int _integer = 10;
  /** RegularExpression Id. */
  int _double = 11;
  /** RegularExpression Id. */
  int _bool = 12;
  /** RegularExpression Id. */
  int _date = 13;
  /** RegularExpression Id. */
  int _datetime = 14;
  /** RegularExpression Id. */
  int crear = 15;
  /** RegularExpression Id. */
  int usar = 16;
  /** RegularExpression Id. */
  int alterar = 17;
  /** RegularExpression Id. */
  int eliminar = 18;
  /** RegularExpression Id. */
  int base_datos = 19;
  /** RegularExpression Id. */
  int tabla = 20;
  /** RegularExpression Id. */
  int objeto = 21;
  /** RegularExpression Id. */
  int procedimiento = 22;
  /** RegularExpression Id. */
  int funcion = 23;
  /** RegularExpression Id. */
  int usuario = 24;
  /** RegularExpression Id. */
  int nulo = 25;
  /** RegularExpression Id. */
  int no_nulo = 26;
  /** RegularExpression Id. */
  int llave_primaria = 27;
  /** RegularExpression Id. */
  int llave_foranea = 28;
  /** RegularExpression Id. */
  int unico = 29;
  /** RegularExpression Id. */
  int autoincrementable = 30;
  /** RegularExpression Id. */
  int colocar = 31;
  /** RegularExpression Id. */
  int password = 32;
  /** RegularExpression Id. */
  int quitar = 33;
  /** RegularExpression Id. */
  int agregar = 34;
  /** RegularExpression Id. */
  int cambiar = 35;
  /** RegularExpression Id. */
  int insertar = 36;
  /** RegularExpression Id. */
  int seleccionar = 37;
  /** RegularExpression Id. */
  int actualizar = 38;
  /** RegularExpression Id. */
  int borrar = 39;
  /** RegularExpression Id. */
  int en = 40;
  /** RegularExpression Id. */
  int de = 41;
  /** RegularExpression Id. */
  int donde = 42;
  /** RegularExpression Id. */
  int valores = 43;
  /** RegularExpression Id. */
  int ordenar = 44;
  /** RegularExpression Id. */
  int por = 45;
  /** RegularExpression Id. */
  int asc = 46;
  /** RegularExpression Id. */
  int desc = 47;
  /** RegularExpression Id. */
  int otorgar = 48;
  /** RegularExpression Id. */
  int denegar = 49;
  /** RegularExpression Id. */
  int permisos = 50;
  /** RegularExpression Id. */
  int backup = 51;
  /** RegularExpression Id. */
  int restaurar = 52;
  /** RegularExpression Id. */
  int usqldump = 53;
  /** RegularExpression Id. */
  int completo = 54;
  /** RegularExpression Id. */
  int declarar = 55;
  /** RegularExpression Id. */
  int si = 56;
  /** RegularExpression Id. */
  int sino = 57;
  /** RegularExpression Id. */
  int para = 58;
  /** RegularExpression Id. */
  int selecciona = 59;
  /** RegularExpression Id. */
  int caso = 60;
  /** RegularExpression Id. */
  int defecto = 61;
  /** RegularExpression Id. */
  int mientras = 62;
  /** RegularExpression Id. */
  int detener = 63;
  /** RegularExpression Id. */
  int retorno = 64;
  /** RegularExpression Id. */
  int contar = 65;
  /** RegularExpression Id. */
  int imprimir = 66;
  /** RegularExpression Id. */
  int get_fecha = 67;
  /** RegularExpression Id. */
  int get_fecha_hora = 68;
  /** RegularExpression Id. */
  int entero = 69;
  /** RegularExpression Id. */
  int doble = 70;
  /** RegularExpression Id. */
  int booleano = 71;
  /** RegularExpression Id. */
  int fecha = 72;
  /** RegularExpression Id. */
  int fecha_hora = 73;
  /** RegularExpression Id. */
  int cadena = 74;
  /** RegularExpression Id. */
  int id = 75;
  /** RegularExpression Id. */
  int var = 76;
  /** RegularExpression Id. */
  int path = 77;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<letra>",
    "<digito>",
    "\"Text\"",
    "\"Integer\"",
    "\"Double\"",
    "\"Bool\"",
    "\"Date\"",
    "\"DateTime\"",
    "\"CREAR\"",
    "\"USAR\"",
    "\"ALTERAR\"",
    "\"ELIMINAR\"",
    "\"BASE_DATOS\"",
    "\"TABLA\"",
    "\"OBJETO\"",
    "\"PROCEDIMIENTO\"",
    "\"FUNCION\"",
    "\"USUARIO\"",
    "\"Nulo\"",
    "\"No Nulo\"",
    "\"Llave_primaria\"",
    "\"Llave_foranea\"",
    "\"Unico\"",
    "\"Autoincrementable\"",
    "\"COLOCAR\"",
    "\"password\"",
    "\"QUITAR\"",
    "\"AGREGAR\"",
    "\"CAMBIAR\"",
    "\"INSERTAR\"",
    "\"SELECCIONAR\"",
    "\"ACTUALIZAR\"",
    "\"BORRAR\"",
    "\"EN\"",
    "\"DE\"",
    "\"DONDE\"",
    "\"VALORES\"",
    "\"ORDENAR\"",
    "\"POR\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"OTORGAR\"",
    "\"DENEGAR\"",
    "\"PERMISOS\"",
    "\"BACKUP\"",
    "\"RESTAURAR\"",
    "\"USQLDUMP\"",
    "\"COMPLETO\"",
    "\"DECLARAR\"",
    "\"SI\"",
    "\"SINO\"",
    "\"PARA\"",
    "\"SELECCIONA\"",
    "\"CASO\"",
    "\"DEFECTO\"",
    "\"MIENTRAS\"",
    "\"DETENER\"",
    "\"RETORNO\"",
    "\"CONTAR\"",
    "\"IMPRIMIR\"",
    "\"FECHA\"",
    "\"FECHA_HORA\"",
    "<entero>",
    "<doble>",
    "<booleano>",
    "<fecha>",
    "<fecha_hora>",
    "<cadena>",
    "<id>",
    "<var>",
    "<path>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=\"",
    "\"*\"",
    "\".\"",
    "\"{\"",
    "\":\"",
    "\"}\"",
    "\"++\"",
    "\"--\"",
    "\"<<\"",
    "\">>\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"^\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
  };

}
